//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolString : DbContext
    {
        public SchoolString()
            : base("name=SchoolString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EducationWorks> EducationWorks { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Notices> Notices { get; set; }
        public DbSet<StudyWorks> StudyWorks { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
        public DbSet<Show> Show { get; set; }
        public DbSet<Profession> Profession { get; set; }
        public DbSet<Comm> Comm { get; set; }
        public DbSet<ScrollImage> ScrollImage { get; set; }
    }
}
